import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import BottomBar from "../components/Sidebar";
// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyCuS25t8eAGUaAaVYbTBSXCTKYCpgl1wj0",
  authDomain: "budgetoghether.firebaseapp.com",
  databaseURL: "https://budgetoghether-default-rtdb.europe-west1.firebasedatabase.app",
  projectId: "budgetoghether",
  storageBucket: "budgetoghether.appspot.com",
  messagingSenderId: "335193730168",
  appId: "1:335193730168:web:95bfd78fffab2e694f118d"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="app-layout">
          <main className="main-content">{children}</main>
          <BottomBar />
        </div>
      </body>
    </html>
  );
}
