/** @format */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "../lib/utils";
import SideNavbar from "@/components/SideNavbar";
import { getTokens } from "next-firebase-auth-edge";
import { cookies } from "next/headers";
import { notFound } from "next/navigation";
import { clientConfig, serverConfig } from "../../config";

export const dynamic = 'force-dynamic'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  const tokens = await getTokens(cookies(), {
    apiKey: clientConfig.apiKey,
    cookieName: serverConfig.cookieName,
    cookieSignatureKeys: serverConfig.cookieSignatureKeys,
    serviceAccount: serverConfig.serviceAccount
  });
  if (tokens) {
    return (
      <html lang="en">
        <body
          className={cn(
            "min-h-screen w-full bg-white text-black flex ",
            inter.className,
            {
              "debug-screens": process.env.NODE_ENV === "development"
            }
          )}
        >
          {/* sidebar */}
          {/* <p className="border">Sidebar</p> */}
          <SideNavbar />
          {/* main page */}
          <div className="p-8 w-full">{children}</div>
        </body>
      </html>
    );
  }
  else {
    return(
    <html lang="en"><body>
      <div className="p-8 w-full">{children}</div>
    </body></html>)
  }
} 