/** @format */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "../lib/utils";
import SideNavbar from "@/components/SideNavbar";
import { getTokens } from "next-firebase-auth-edge";
import { cookies } from "next/headers";
import { notFound } from "next/navigation";
import { clientConfig, serverConfig } from "../../config";

export const dynamic = 'force-dynamic'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
    return (
      <html lang="en">
        <body
          className={cn(
            "min-h-screen w-full flex flex-col items-center justify-center",
            inter.className,
            {
              "debug-screens": process.env.NODE_ENV === "development"
            }
          )}
        >
          {/* main page */}
          <div className="w-full max-w max-h p-6 bg-white rounded-lg">{children}</div>
        </body>
      </html>
    );
} 